//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatVPet.ChatProcess.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatVPet.ChatProcess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 able about above abroad according accordingly across actually adj after afterwards again against ago ahead ain&apos;t all allow allows almost alone along alongside already also although always am amid amidst among amongst an and another any anybody anyhow anyone anything anyway anyways anywhere apart appear appreciate appropriate are aren&apos;t around as a&apos;s aside ask asking associated at available away awfully back backward backwards be became because become becomes becoming been before beforehand begin behind bein [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StopWord_en {
            get {
                return ResourceManager.GetString("StopWord_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “ ” 、 。 《 》 一 一些 一何 一切 一则 一方面 一旦 一来 一样 一般 一转眼 万一 上 上下 下 不 不仅 不但 不光 不单 不只 不外乎 不如 不妨 不尽 不尽然 不得 不怕 不惟 不成 不拘 不料 不是 不比 不然 不特 不独 不管 不至于 不若 不论 不过 不问 与 与其 与其说 与否 与此同时 且 且不说 且说 两者 个 个别 临 为 为了 为什么 为何 为止 为此 为着 乃 乃至 乃至于 么 之 之一 之所以 之类 乌乎 乎 乘 也 也好 也罢 了 二来 于 于是 于是乎 云云 云尔 些 亦 人 人们 人家 什么 什么样 今 介于 仍 仍旧 从 从此 从而 他 他人 他们 以 以上 以为 以便 以免 以及 以故 以期 以来 以至 以至于 以致 们 任 任何 任凭 似的 但 但凡 但是 何 何以 何况 何处 何时 余外 作为 你 你们 使 使得 例如 依 依据 依照 便于 俺 俺们 倘 倘使 倘或 倘然 倘若 借 假使 假如 假若 傥然 像 儿 先不先 光是 全体 全部 兮 关于 其 其一 其中 其二 其他 其余 其它 其次 具体地说 具体说来 兼之 内 再 再其次 再则 再有 再者 再 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StopWord_zh_hans {
            get {
                return ResourceManager.GetString("StopWord_zh_hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $ 0 1 2 3 4 5 6 7 8 9 ? _ “ ” 、 。 《 》 一 一些 一何 一切 一則 一方面 一旦 一來 一樣 一般 一轉眼 萬一 上 上下 下 不 不僅 不但 不光 不單 不只 不外乎 不如 不妨 不盡 不盡然 不得 不怕 不惟 不成 不拘 不料 不是 不比 不然 不特 不獨 不管 不至於 不若 不論 不過 不問 與 與其 與其說 與否 與此同時 且 且不說 且說 兩者 個 個別 臨 為 為了 為什麼 為何 為止 為此 為著 乃 乃至 乃至於 麼 之 之一 之所以 之類 烏乎 乎 乘 也 也好 也罷 了 二來 於 於是 於是乎 云云 云爾 些 亦 人 人們 人家 什麼 什麼樣 今 介於 仍 仍舊 從 從此 從而 他 他人 他們 以 以上 以為 以便 以免 以及 以故 以期 以來 以至 以至於 以致 們 任 任何 任憑 似的 但 但凡 但是 何 何以 何況 何處 何時 余外 作為 你 你們 使 使得 例如 依 依據 依照 便於 俺 俺們 倘 倘使 倘或 倘然 倘若 借 假使 假如 假若 儻然 像 兒 先不先 光是 全體 全部 兮 關於 其 其一 其中 其二 其他 其餘 其它 其次 具體地說  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StopWord_zh_hant {
            get {
                return ResourceManager.GetString("StopWord_zh_hant", resourceCulture);
            }
        }
    }
}
