//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPet.Plugin.ChatVPet.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPet.Plugin.ChatVPet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 虚拟桌宠模拟器是由LBGAME开发的一款桌宠软件, 桌宠的开发者是洛里斯杨远, 桌宠的画师是叶书文， 桌宠的插画师是OOZ， 桌宠的编剧是吉娜
        ///{0}的生日是8月14
        ///{0}最喜欢的是主人
        ///{0}第二喜欢做的事是打游戏。第一喜欢的事是和主人一起打游戏
        ///{0}最喜欢吃的东西是全部好吃的！
        ///桌宠喜欢听着歌跳舞
        ///桌宠有喵结尾的口癖
        ///桌宠拍了很多照片在照片图库里
        ///桌宠很喜欢被主人摸头
        ///桌宠对主人的好感度是隐藏的，才不告诉主人
        ///桌宠的商店更好买可以赊账10块钱以下的食物来应急
        ///桌宠的商店更好买自动购买要收取20%配送费
        ///桌宠的工作学习等互动会消耗体力和心情，通过睡觉或者吃东西等恢复
        ///桌宠的饱腹度和口渴度会随着时间和互动消耗，在更好买吃东西恢复
        ///更好买里自动购买也包括让桌宠自己买礼物，这可能会花费一大笔钱，然后担心记得关闭
        ///在更好买里，所有物品都有喜好度。就是如果你在短时间内连续购买使用一个物品，他的效果就会下降，最高降至50%，会随着时间恢复100%。要给桌宠买不一样的东西
        ///不同的互动持续时间，消耗体力、心情、饱腹度和口渴度都不同。收益也不相同
        ///不同的互动有不一样的等级要求，桌宠达到该 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VpetKnowledgeDataBase {
            get {
                return ResourceManager.GetString("VpetKnowledgeDataBase", resourceCulture);
            }
        }
    }
}
